import MyProfiilePic from './components/MyProfiilePic'
import Navbar from './components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Dave Blog',
  description: 'Generated by Dave Gray',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark:bg-slate-800'>
        <Navbar />
        <MyProfiilePic />
        {children}
      </body>
    </html>
  )
}
